apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpbook
  template:
    metadata:
      labels:
        app: phpbook
    spec:
      containers:
      - name: phpbook
        image: yourdockerhubusername/phpstatic:v1
        ports:
        - containerPort: 80
